apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: digital-user-namespace-creator
subjects:
- kind: User
  name: digital-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: capsule-namespace-creator
  apiGroup: rbac.authorization.k8s.io