apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-core-banking-etcd-0
  namespace: core-banking-vcluster
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi