# vCluster configuration without persistent storage
sync:
  toHost:
    pods:
      enabled: true

storage:
  persistence: false

controlPlane:
  backingStore:
    etcd:
      embedded:
        enabled: true